insert into dms_questions (id, bloco, ordem, pergunta, subtexto, opcoes, versao, ativa) values
('q1', 'infraestrutura', 1,
 'Onde os dados da empresa estão armazenados hoje?',
 null,
 '[{"valor":1,"label":"Planilhas e arquivos soltos"},{"valor":2,"label":"Sistema principal, sem integração"},{"valor":3,"label":"Banco de dados centralizado"},{"valor":4,"label":"Banco de dados com cloud estruturada"}]',
 1, true),

('q2', 'infraestrutura', 2,
 'Existe processo automatizado de coleta dos dados?',
 'Considere ERPs, CRMs, formulários e integrações entre sistemas.',
 '[{"valor":1,"label":"Tudo manual"},{"valor":2,"label":"Coleta automatizada em parte dos fluxos"},{"valor":3,"label":"Automatizada na maior parte dos fluxos"},{"valor":4,"label":"Pipeline de ingestão ponta a ponta"}]',
 1, true),

('q3', 'infraestrutura', 3,
 'Existe backup e proteção formal dos dados?',
 'LGPD, criptografia, controle de acessos.',
 '[{"valor":1,"label":"Não existe política"},{"valor":2,"label":"Backups manuais"},{"valor":3,"label":"Backups automatizados"},{"valor":4,"label":"Backup e segurança auditada"}]',
 1, true),

('q4', 'governanca', 4,
 'Quem responde pelos dados dentro da empresa?',
 null,
 '[{"valor":1,"label":"Ninguém definido"},{"valor":2,"label":"Um analista cuida informalmente"},{"valor":3,"label":"Pessoa ou time formalmente responsável"},{"valor":4,"label":"Time com processo de qualidade ativo"}]',
 1, true),

('q5', 'governanca', 5,
 'O significado e o cálculo dos dados estão documentados?',
 'Alguém que entra na empresa hoje consegue entender o que cada dado significa?',
 '[{"valor":1,"label":"Não existe documentação"},{"valor":2,"label":"Documentação informal e incompleta"},{"valor":3,"label":"Documentação parcial dos dados principais"},{"valor":4,"label":"Documentação completa e atualizada"}]',
 1, true),

('q6', 'governanca', 6,
 'Os dados de sistemas diferentes batem entre si?',
 null,
 '[{"valor":1,"label":"Inconsistências frequentes"},{"valor":2,"label":"Inconsistências ocasionais, sem monitoramento"},{"valor":3,"label":"Poucas inconsistências, validação pontual"},{"valor":4,"label":"Consistentes, com validação ativa"}]',
 1, true),

('q7', 'cultura', 7,
 'Como as decisões mais importantes são tomadas?',
 null,
 '[{"valor":1,"label":"Por intuição e experiência"},{"valor":2,"label":"Dados consultados só em momento de crise"},{"valor":3,"label":"Dashboards consultados regularmente pela liderança"},{"valor":4,"label":"Decisões rastreáveis em dados, em todos os níveis"}]',
 1, true),

('q8', 'cultura', 8,
 'Existem KPIs por área, medidos e revisados com regularidade?',
 null,
 '[{"valor":1,"label":"Não definidos"},{"valor":2,"label":"Definidos, mas não medidos"},{"valor":3,"label":"Medidos parcialmente"},{"valor":4,"label":"Medidos e revisados em rito formal"}]',
 1, true),

('q9', 'ia', 9,
 'A área usa IA generativa no dia a dia?',
 null,
 '[{"valor":1,"label":"Não usa"},{"valor":2,"label":"Uso pessoal, sem padrão"},{"valor":3,"label":"Casos de uso definidos"},{"valor":4,"label":"Integrada em produtos e processos"}]',
 1, true),

('q10', 'ia', 10,
 'Existe política de uso de IA e prompts?',
 'Privacidade, segurança e compliance.',
 '[{"valor":1,"label":"Não existe"},{"valor":2,"label":"Diretrizes informais"},{"valor":3,"label":"Política documentada"},{"valor":4,"label":"Política com treinamento do time"}]',
 1, true),

('q11', 'ia', 11,
 'Há automações com agentes ou RAG sobre dados próprios da empresa?',
 'RAG é a técnica que permite a uma IA responder com base nos documentos e dados da própria empresa.',
 '[{"valor":1,"label":"Não"},{"valor":2,"label":"Provas de conceito isoladas"},{"valor":3,"label":"Casos em produção"},{"valor":4,"label":"Plataforma de agentes ativa"}]',
 1, true),

('q12', 'ia', 12,
 'Tarefas repetitivas são automatizadas?',
 null,
 '[{"valor":1,"label":"Tudo manual"},{"valor":2,"label":"Automações isoladas"},{"valor":3,"label":"Automações em fluxos críticos"},{"valor":4,"label":"Operação majoritariamente automatizada"}]',
 1, true),

('q13', 'ia', 13,
 'Quais ferramentas de automação a empresa usa?',
 null,
 '[{"valor":1,"label":"Nenhuma"},{"valor":2,"label":"Macros ou scripts pontuais"},{"valor":3,"label":"No-code (Zapier, Make, n8n)"},{"valor":4,"label":"Plataforma própria com código"}]',
 1, true),

('q14', 'ia', 14,
 'Existe monitoramento dos jobs e automações em produção?',
 'Alguém sabe quando uma automação falha, e como?',
 '[{"valor":1,"label":"Sem monitoramento"},{"valor":2,"label":"Checagem manual"},{"valor":3,"label":"Alertas automáticos"},{"valor":4,"label":"SLA e observabilidade"}]',
 1, true),

('q15', 'ia', 15,
 'Quanto tempo por mês as automações economizam?',
 'Estimativa aproximada.',
 '[{"valor":1,"label":"Nada mensurável"},{"valor":2,"label":"Algumas horas"},{"valor":3,"label":"Dezenas de horas"},{"valor":4,"label":"Centenas de horas"}]',
 1, true),

('q16', 'ia', 16,
 'A empresa usa modelos preditivos?',
 'Previsão de demanda, churn, scoring de clientes.',
 '[{"valor":1,"label":"Não usa"},{"valor":2,"label":"Provas de conceito isoladas"},{"valor":3,"label":"Modelos em produção"},{"valor":4,"label":"Vários modelos em produção"}]',
 1, true),

('q17', 'ia', 17,
 'Como esses modelos são desenvolvidos e versionados?',
 null,
 '[{"valor":1,"label":"Não há processo"},{"valor":2,"label":"Notebooks ad-hoc"},{"valor":3,"label":"Repositório versionado"},{"valor":4,"label":"Pipeline de MLOps completo"}]',
 1, true),

('q18', 'ia', 18,
 'Os modelos em produção são monitorados?',
 'Queda de performance, mudança de comportamento dos dados.',
 '[{"valor":1,"label":"Não monitoramos"},{"valor":2,"label":"Checagens manuais"},{"valor":3,"label":"Métricas automatizadas"},{"valor":4,"label":"Monitoramento contínuo com retraining"}]',
 1, true),

('q19', 'ia', 19,
 'Como a empresa mede o retorno das iniciativas de IA?',
 null,
 '[{"valor":1,"label":"Não medimos"},{"valor":2,"label":"Percepção qualitativa"},{"valor":3,"label":"Métrica por caso de uso"},{"valor":4,"label":"Painel consolidado de ROI"}]',
 1, true),

('q20', 'ia', 20,
 'Existe responsável definido por operar e sustentar as soluções de IA após a entrega?',
 null,
 '[{"valor":1,"label":"Ninguém responsável"},{"valor":2,"label":"Responsabilidade informal"},{"valor":3,"label":"Pessoa ou time com dedicação parcial"},{"valor":4,"label":"Time dedicado com rotina de operação"}]',
 1, true);
